import { Injectable } from 'angular2/core';

@Injectable()
export class DatabaseService{
	getWhiteCards(){
		return Promise.resolve(WHITE_CARDS);
	}
  getBlackCards(){
    return Promise.resolve(BLACK_CARDS);
  }
}

export interface BlackCard{
  text: string;
  spaces: number;
}
export interface WhiteCard{
  text: string;
}
export var WHITE_CARDS: WhiteCard[] =[
{"text":"Tweeting."},
{"text":"2 Girls 1 Cup."},
{"text":"50,000 volts straight to the nipples."},
{"text":"72 virgins."},
{"text":"8 oz. of sweet Mexican black-tar heroin."},
{"text":"A bag of magic beans."},
{"text":"A balanced breakfast."},
{"text":"A ball of earwax, semen, and toenail clippings."},
{"text":"A big hoopla about nothing."},
{"text":"A bitch slap."},
{"text":"A bleached asshole."},
{"text":"A Bop It™."},
{"text":"A brain tumor."},
{"text":"A bucket of fish heads."},
{"text":"A can of whoop-ass."},
{"text":"A caress of the inner thigh"},
{"text":"A cartoon camel enjoying the smooth, refreshing taste of a cigarette."},
{"text":"A clandestine butt scratch."},
{"text":"A cooler full of organs."},
{"text":"A death ray."},
{"text":"A defective condom."},
{"text":"A disappointing birthday party."},
{"text":"A drive-by shooting."},
{"text":"A falcon with a cap on its head."},
{"text":"A fetus."},
{"text":"A Fleshlight."},
{"text":"A foul mouth."},
{"text":"A gassy antelope."},
{"text":"A gentle caress of the inner thigh."},
{"text":"A good sniff."},
{"text":"A grande sugar-free iced soy caramel macchiato."},
{"text":"A Gypsy curse."},
{"text":"A homoerotic volleyball montage."},
{"text":"A hot mess."},
{"text":"A LAN party."},
{"text":"A lifetime of sadness."},
{"text":"A live studio audience."},
{"text":"A look-see."},
{"text":"A man on the brink of orgasm."},
{"text":"A mating display."},
{"text":"A micropenis."},
{"text":"A micropig wearing a tiny raincoat and booties."},
{"text":"A middle-aged man on roller skates."},
{"text":"A mime having a stroke."},
{"text":"A moment of silence."},
{"text":"A monkey smoking a cigar."},
{"text":"A mopey zoo lion."},
{"text":"A murder most foul."},
{"text":"A neglected Tamagotchi™."},
{"text":"A pyramid of severed heads."},
{"text":"A really cool hat."},
{"text":"A robust mongoloid."},
{"text":"A sad handjob."},
{"text":"A salty surprise."},
{"text":"A sassy black woman."},
{"text":"A sausage festival."},
{"text":"A saxophone solo."},
{"text":"A sea of troubles."},
{"text":"A snapping turtle biting the tip of your penis."},
{"text":"A spastic nerd."},
{"text":"A stray pube."},
{"text":"A subscription to Men's Fitness."},
{"text":"A Super Soaker™ full of cat pee."},
{"text":"A thermonuclear detonation."},
{"text":"A time travel paradox."},
{"text":"A tiny horse."},
{"text":"A tribe of warrior women."},
{"text":"A vajazzled vagina."},
{"text":"A wheelchair death race."},
{"text":"A windmill full of corpses."},
{"text":"A wisecracking terrorist."},
{"text":"A zesty breakfast burrito."},
{"text":"Aaron Burr."},
{"text":"Abstinence."},
{"text":"Accidentally slipping yourself a roofie."},
{"text":"Active listening."},
{"text":"Actually taking candy from a baby."},
{"text":"Adderall™."},
{"text":"Adult Friendfinder."},
{"text":"Advice from a wise, old black man."},
{"text":"African children"},
{"text":"Agriculture."},
{"text":"AIDS."},
{"text":"Alcoholism."},
{"text":"All-you-can-eat shrimp for $4.99."},
{"text":"Altar boys."},
{"text":"America."},
{"text":"American Gladiators."},
{"text":"Amputees."},
{"text":"An asymmetric boob job."},
{"text":"An endless stream of diarrhea."},
{"text":"An erection that lasts longer than four hours."},
{"text":"An honest cop with nothing left to lose."},
{"text":"An icepick labotomy."},
{"text":"An M. Night Shyamalan plot twist."},
{"text":"An M16 assault rifle."},
{"text":"An Oedipus complex."},
{"text":"An oversized lollipop."},
{"text":"An ugly face."},
{"text":"An uppercut."},
{"text":"Anal beads."},
{"text":"Another goddamn vampire movie."},
{"text":"Arnold Schwarzenegger."},
{"text":"Asians who aren't good at math."},
{"text":"Assless chaps."},
{"text":"Attitude."},
{"text":"Auschwitz."},
{"text":"Authentic Mexican cuisine."},
{"text":"Autocannibalism."},
{"text":"AXE Body Spray."},
{"text":"Balls."},
{"text":"Bananas in Pajamas."},
{"text":"Barack Obama."},
{"text":"BATMAN!!!"},
{"text":"Battlefield amputations."},
{"text":"Becoming a blueberry."},
{"text":"Bees?"},
{"text":"Being a dick to children."},
{"text":"Being a motherfucking sorcerer."},
{"text":"Being fabulous."},
{"text":"Being fat and stupid."},
{"text":"Being marginalized."},
{"text":"Being on fire."},
{"text":"Being rich."},
{"text":"Bestiality."},
{"text":"Bill Nye the Science Guy."},
{"text":"Bingeing and purging."},
{"text":"Bio-engineered assault turtles with acid breath."},
{"text":"Bitches."},
{"text":"Black people."},
{"text":"Bling."},
{"text":"Bond, James Bond."},
{"text":"Bono."},
{"text":"Booby-trapping the house to foil burglars."},
{"text":"Boogers."},
{"text":"Breaking out into song and dance."},
{"text":"Britney Spears at 55."},
{"text":"Brown people."},
{"text":"Canned tuna with extra dolphin."},
{"text":"Capturing Newt Gingrich and forcing him to dance in a monkey suit."},
{"text":"Cards Against Humanity."},
{"text":"Catapults."},
{"text":"Centaurs."},
{"text":"Chainsaws for hands."},
{"text":"Charisma."},
{"text":"Cheating in the Special Olympics."},
{"text":"Child abuse."},
{"text":"Child beauty pageants."},
{"text":"Children on leashes."},
{"text":"Chivalry."},
{"text":"Christopher Walken."},
{"text":"Chunks of dead hitchhiker."},
{"text":"Chunks of dead prostitute."},
{"text":"Chutzpah."},
{"text":"Civilian casualties."},
{"text":"Classist undertones."},
{"text":"Coat hanger abortions."},
{"text":"Cockfights."},
{"text":"College."},
{"text":"Concealing a boner."},
{"text":"Consensual sex."},
{"text":"Consultants."},
{"text":"Cookie Monster devouring the Eucharist wafers."},
{"text":"Copping a feel."},
{"text":"Count Chocula."},
{"text":"Court-ordered rehab."},
{"text":"Creed."},
{"text":"Crippling debt."},
{"text":"Crucifixion."},
{"text":"Crumbs all over the god damn carpet."},
{"text":"Crumpets with the Queen."},
{"text":"Crystal meth."},
{"text":"Cuddling."},
{"text":"Customer service representatives."},
{"text":"Cybernetic enhancements."},
{"text":"Daddy issues."},
{"text":"Daniel Radcliffe's delicious asshole."},
{"text":"Dark and mysterious forces beyond our control."},
{"text":"Darth Vader."},
{"text":"Date rape."},
{"text":"Dave Matthews Band."},
{"text":"David Bowie flying in on a tiger made of lightning."},
{"text":"Dead babies."},
{"text":"Dead parents."},
{"text":"Dental dams."},
{"text":"Destroying the evidence."},
{"text":"Dick Cheney"},
{"text":"Dick fingers."},
{"text":"Doin' it in the butt."},
{"text":"Doing the right thing."},
{"text":"Domino's™ Oreo™ Dessert Pizza."},
{"text":"Donald Trump."},
{"text":"Douchebags on their iPhones."},
{"text":"Dr. Martin Luther King, Jr."},
{"text":"Drinking alone."},
{"text":"Dropping a chandelier on your enemies and riding the rope up."},
{"text":"Drum circles."},
{"text":"Dry heaving."},
{"text":"Dwarf tossing."},
{"text":"Dying of dysentery."},
{"text":"Dying."},
{"text":"Eastern European Turbo-Folk music."},
{"text":"Eating all of the cookies before the AIDS bake-sale."},
{"text":"Eating the last known bison."},
{"text":"Eating too much of a lamp."},
{"text":"Edible underpants."},
{"text":"Elderly Japanese men."},
{"text":"Electricity."},
{"text":"Embryonic stem cells."},
{"text":"Emma Watson."},
{"text":"Emotions."},
{"text":"Erectile dysfunction."},
{"text":"Establishing Dominance."},
{"text":"Estrogen."},
{"text":"Ethnic cleansing."},
{"text":"Eugenics."},
{"text":"Euphoria™ by Calvin Klein."},
{"text":"Exactly what you'd expect."},
{"text":"Exchanging pleasantries."},
{"text":"Existentialists."},
{"text":"Expecting a burp and vomiting on the floor."},
{"text":"Explosions."},
{"text":"Extremely tight pants."},
{"text":"Faith healing."},
{"text":"FALCON PUNCH!!!"},
{"text":"Famine."},
{"text":"Fancy Feast®."},
{"text":"Farting and walking away."},
{"text":"Farting into your petticoats and wafting it at Lord Gregory."},
{"text":"Fear itself."},
{"text":"Feeding Rosie O'Donnell."},
{"text":"Fiery poops."},
{"text":"Figgy pudding."},
{"text":"Filling Sean Hannity with helium and watching him float away."},
{"text":"Finger painting."},
{"text":"Fingering."},
{"text":"Firing a rifle into the air while balls deep in a squealing hog."},
{"text":"Five-Dollar Footlongs™."},
{"text":"Flash flooding."},
{"text":"Flavored condoms."},
{"text":"Flesh-eating bacteria."},
{"text":"Flightless birds."},
{"text":"Flying sex snakes."},
{"text":"Foreskin."},
{"text":"Forgetting the Alamo."},
{"text":"Former President George W. Bush."},
{"text":"Four Loko."},
{"text":"Free samples."},
{"text":"Friction."},
{"text":"Friendly fire."},
{"text":"Friends who eat all the snacks."},
{"text":"Friends with benefits."},
{"text":"Frolicking."},
{"text":"Front butt."},
{"text":"Full frontal nudity."},
{"text":"Funky fresh rhymes."},
{"text":"Gandhi."},
{"text":"Garth Brooks."},
{"text":"Gary Coleman."},
{"text":"Geese."},
{"text":"Genghis Khan."},
{"text":"Genital piercings."},
{"text":"Genuine human connection."},
{"text":"German dungeon porn."},
{"text":"Getting drunk on mouthwash."},
{"text":"Getting married, having a few kids, buying some stuff, retiring to Florida, and dying."},
{"text":"Getting naked and watching Nickelodeon."},
{"text":"Getting really high."},
{"text":"Getting so angry that you pop a boner."},
{"text":"Ghosts."},
{"text":"Girls who shouldn't go wild."},
{"text":"Giving 110%"},
{"text":"Giving birth to the Antichrist."},
{"text":"Glenn Beck being harried by a swarm of buzzards."},
{"text":"Glenn Beck catching his scrotum on a curtain hook."},
{"text":"Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts."},
{"text":"Glenn Beck."},
{"text":"Global warming."},
{"text":"Gloryholes."},
{"text":"Goats eating cans."},
{"text":"Goats eating coins."},
{"text":"Goblins."},
{"text":"God."},
{"text":"GoGurt®."},
{"text":"Golden showers."},
{"text":"Grandma."},
{"text":"Grave robbing."},
{"text":"Growing a pair."},
{"text":"Guys who don't call."},
{"text":"Half-assed foreplay."},
{"text":"Harry Potter erotica."},
{"text":"Have some more kugel."},
{"text":"Having anuses for eyes."},
{"text":"Heartwarming orphans."},
{"text":"Heath Ledger."},
{"text":"Helplessly giggling at the mention of Hutus and Tutsis."},
{"text":"Her Majesty, Queen Elizabeth II."},
{"text":"Her Royal Highness, Queen Elizabeth II."},
{"text":"Heteronormativity."},
{"text":"Hip hop jewels"},
{"text":"Historically black colleges."},
{"text":"Holding down a child and farting all over him."},
{"text":"Home video of Oprah sobbing into a Lean Cuisine®."},
{"text":"Homeless people."},
{"text":"Hope."},
{"text":"Hormone injections."},
{"text":"Horrifying laser hair removal accidents."},
{"text":"Horse meat."},
{"text":"Hospice care."},
{"text":"Hot cheese."},
{"text":"Hot people."},
{"text":"Hot Pockets®."},
{"text":"Hulk Hogan."},
{"text":"Hunting "},
{"text":"Hurricane Katrina."},
{"text":"I'm friends with your dad on Facebook."},
{"text":"Impotence."},
{"text":"Improvised explosive devices."},
{"text":"Inappropriate yelling."},
{"text":"Inappropriate yodeling."},
{"text":"Incest."},
{"text":"Inserting a Mason jar into my anus."},
{"text":"Intelligent design."},
{"text":"Invading Poland."},
{"text":"Irritable Bowel Syndrome."},
{"text":"Italians."},
{"text":"Jerking off into a pool of children's tears."},
{"text":"Jew-fros."},
{"text":"Jewish fraternities."},
{"text":"Jibber-jabber."},
{"text":"Jobs."},
{"text":"Joe Biden."},
{"text":"John Wilkes Booth"},
{"text":"Judge Judy."},
{"text":"Justin Bieber."},
{"text":"Kamikaze pilots."},
{"text":"Kanye West."},
{"text":"Keanu Reeves."},
{"text":"Keeping Christ in Christmas."},
{"text":"Keg stands."},
{"text":"Kibbles n' Bits."},
{"text":"Kids with ass cancer."},
{"text":"Kim Jong-il."},
{"text":"Lactation."},
{"text":"Lady Gaga."},
{"text":"Lance Armstrong's missing testicle."},
{"text":"Land mines."},
{"text":"Laying an egg."},
{"text":"Leaving an awkward voicemail."},
{"text":"Leprosy."},
{"text":"Letting yourself go."},
{"text":"Licking things to claim them as your own."},
{"text":"Lockjaw."},
{"text":"Loose lips."},
{"text":"Lumberjack fantasies."},
{"text":"Lunchables™."},
{"text":"Mad cow disease."},
{"text":"Magnets."},
{"text":"Making a pouty face."},
{"text":"Making sex at her."},
{"text":"Man meat."},
{"text":"Marky Mark and the Funky Bunch."},
{"text":"Martha Stewart."},
{"text":"Masturbation."},
{"text":"Mathletes."},
{"text":"Me time."},
{"text":"MechaHitler."},
{"text":"Men."},
{"text":"Menstrual rage."},
{"text":"Menstruation."},
{"text":"Michael Jackson."},
{"text":"Michelle Obama's arms."},
{"text":"Miley Cyrus at 55."},
{"text":"Mistaking a retarded person for someone who's merely deaf."},
{"text":"Morgan Freeman's voice."},
{"text":"Mountain Dew Code Red."},
{"text":"Mouth herpes."},
{"text":"Mr. Clean, right behind you."},
{"text":"Mr. Snuffleupagus."},
{"text":"Muhammad (Praise Be Unto Him)."},
{"text":"Multiple stab wounds."},
{"text":"Mutually-assured destruction."},
{"text":"Muzzy."},
{"text":"My black ass."},
{"text":"My collection of high-tech sex toys."},
{"text":"My ex-wife."},
{"text":"My genitals."},
{"text":"My humps."},
{"text":"My inner demons."},
{"text":"My relationship status."},
{"text":"My sex life."},
{"text":"My soul."},
{"text":"My vagina."},
{"text":"Natalie Portman."},
{"text":"Natural male enhancement."},
{"text":"Natural selection."},
{"text":"Nazis."},
{"text":"Necrophilia."},
{"text":"New Age music."},
{"text":"Nickelback."},
{"text":"Nicolas Cage."},
{"text":"Nip slips."},
{"text":"Nipple blades."},
{"text":"Nocturnal emissions."},
{"text":"Not giving a shit about the Third World."},
{"text":"Not reciprocating oral sex."},
{"text":"Not wearing pants."},
{"text":"Obesity."},
{"text":"Object permanence."},
{"text":"Old-people smell."},
{"text":"One trillion dollars."},
{"text":"Oompa-Loompas."},
{"text":"Opposable thumbs."},
{"text":"Our first chimpanzee President."},
{"text":"Overcompensation."},
{"text":"Oversized lollipops."},
{"text":"Pabst Blue Ribbon."},
{"text":"Pac-Man uncontrollably guzzling cum."},
{"text":"Panda sex."},
{"text":"Paris Hilton."},
{"text":"Parting the Red Sea."},
{"text":"Party poopers."},
{"text":"Passable transvestites."},
{"text":"Passing a kidney stone."},
{"text":"Passive-aggression."},
{"text":"Passive-aggressive Post-it notes."},
{"text":"PCP."},
{"text":"Peanut Butter Jelly Time."},
{"text":"Pedophiles."},
{"text":"Peeing a little bit."},
{"text":"Penis breath."},
{"text":"Penis envy."},
{"text":"People who smell their own socks."},
{"text":"Picking up girls at the abortion clinic."},
{"text":"Pictures of boobs."},
{"text":"Pixelated bukkake."},
{"text":"Police Brutality."},
{"text":"Pooping back and forth. Forever."},
{"text":"Pooping in the soup."},
{"text":"Poopy diapers."},
{"text":"Poor life choices."},
{"text":"Poor people."},
{"text":"Poorly-timed Holocaust jokes."},
{"text":"Popped collars."},
{"text":"Porn stars."},
{"text":"Powerful thighs."},
{"text":"Prancing."},
{"text":"Praying the gay away."},
{"text":"Preteens."},
{"text":"Pretending to care."},
{"text":"Prosti-tots."},
{"text":"Pterodactyl eggs."},
{"text":"Puberty."},
{"text":"Public ridicule."},
{"text":"Pulling out."},
{"text":"Puppies!"},
{"text":"Queefing."},
{"text":"Racially-biased SAT questions."},
{"text":"Racism."},
{"text":"Raping and pillaging."},
{"text":"Raptor attacks."},
{"text":"Re-gifting."},
{"text":"Rehab."},
{"text":"Repression."},
{"text":"Republicans."},
{"text":"Riding off into the sunset."},
{"text":"Ring Pops™."},
{"text":"Rip Torn dropkicking anti-Semitic lesbians."},
{"text":"Road head."},
{"text":"Robbing a sperm bank."},
{"text":"Robert Downey, Jr."},
{"text":"RoboCop."},
{"text":"Ronald Reagan."},
{"text":"Roofies."},
{"text":"Running out of semen."},
{"text":"Rush Limbaugh's soft, shitty body."},
{"text":"Same-sex ice dancing."},
{"text":"Sarah Palin."},
{"text":"Saxophone solos."},
{"text":"Saying "},
{"text":"Scalping."},
{"text":"Science."},
{"text":"Scientology."},
{"text":"Scrubbing under the folds."},
{"text":"Sean Connery."},
{"text":"Sean Penn."},
{"text":"Seduction."},
{"text":"Seeing Grandma naked."},
{"text":"Self-loathing."},
{"text":"Seppuku."},
{"text":"Serfdom."},
{"text":"Sex with Patrick Stewart."},
{"text":"Sexting."},
{"text":"Sexual peeing."},
{"text":"Sexual tension."},
{"text":"Sexy pillow fights."},
{"text":"Shapeshifters."},
{"text":"Shaquille O'Neal's acting career."},
{"text":"Sharing needles."},
{"text":"Shiny objects."},
{"text":"Shorties and blunts."},
{"text":"Showing up to an orgy for the food."},
{"text":"Silence."},
{"text":"Sipping artificial popcorn butter."},
{"text":"Skeletor."},
{"text":"Smallpox blankets."},
{"text":"Smegma."},
{"text":"Sniffing glue."},
{"text":"Sobbing into a Hungry-Man™ Frozen Dinner"},
{"text":"Soiling oneself."},
{"text":"Some god-damn peace and quiet."},
{"text":"Soup that is too hot."},
{"text":"Spectacular abs."},
{"text":"Sperm whales."},
{"text":"Spontaneous human combustion."},
{"text":"Stalin."},
{"text":"Stephen Hawking talking dirty."},
{"text":"Steve Irwin."},
{"text":"Stifling a giggle at the mention of Hutus and Tutsis."},
{"text":"Stormtroopers."},
{"text":"Stranger danger."},
{"text":"Strong female characters."},
{"text":"Stunt doubles."},
{"text":"Substitute teachers."},
{"text":"Sucking some dicks to not get drafted."},
{"text":"Sunshine and rainbows."},
{"text":"Surprise sex!"},
{"text":"Swag."},
{"text":"Sweet, sweet vengeance."},
{"text":"Switching to Geico®."},
{"text":"Swooping."},
{"text":"Synergistic management solutions."},
{"text":"Take-backsies."},
{"text":"Taking off your shirt."},
{"text":"Tangled Slinkys."},
{"text":"Tasteful sideboob."},
{"text":"Teaching a robot to love."},
{"text":"Team-building exercises."},
{"text":"Teenage pregnancy."},
{"text":"Tentacle porn."},
{"text":"Testicular torsion."},
{"text":"That one gay Teletubby."},
{"text":"That thing that electrocutes your abs."},
{"text":"The American Dream"},
{"text":"The Amish."},
{"text":"The art of seduction."},
{"text":"The Big Bang."},
{"text":"The Blood of Christ."},
{"text":"The Boy Scouts of America."},
{"text":"The Care Bear Stare."},
{"text":"The Chinese gymnastics team."},
{"text":"The chronic."},
{"text":"The clitoris."},
{"text":"The cool, refreshing taste of Pepsi®."},
{"text":"The Dance of the Sugar Plum Fairy."},
{"text":"The deformed."},
{"text":"The Devil Himself."},
{"text":"The Donald Trump Seal of Approval.™"},
{"text":"The drama club."},
{"text":"The entire Mormon Tabernacle Choir."},
{"text":"The female orgasm."},
{"text":"The folly of man."},
{"text":"The forbidden fruit."},
{"text":"The Force."},
{"text":"The gays."},
{"text":"The glass ceiling."},
{"text":"The Great Depression."},
{"text":"The Hamburglar."},
{"text":"The hardworking Mexican."},
{"text":"The heart of a child."},
{"text":"The Holy Bible."},
{"text":"The homosexual agenda."},
{"text":"The homosexual lifestyle."},
{"text":"The Hustle."},
{"text":"The inevitable heat death of the universe."},
{"text":"The invisible hand."},
{"text":"The Jews."},
{"text":"The KKK"},
{"text":"The Kool-Aid Man."},
{"text":"The light of a billion suns."},
{"text":"The Little Engine That Could."},
{"text":"The Make-A-Wish® Foundation."},
{"text":"The milk man."},
{"text":"The miracle of childbirth."},
{"text":"The morbidly obese."},
{"text":"The Patriarchy."},
{"text":"The penny whistle solo from "},
{"text":"The People's Elbow."},
{"text":"The pirate's life."},
{"text":"The placenta."},
{"text":"The plot of a Michael Bay movie."},
{"text":"The Pope."},
{"text":"The profoundly handicapped."},
{"text":"The Rapture."},
{"text":"The Red Menace."},
{"text":"The Rev. Dr. Martin Luther King, Jr."},
{"text":"The rhythms of Africa."},
{"text":"The South."},
{"text":"The Superdome."},
{"text":"The taint; the grundle; the fleshy fun-bridge."},
{"text":"The Tempur-Pedic® Swedish Sleep System™."},
{"text":"The terrorists."},
{"text":"The Thong Song."},
{"text":"The Three-Fifths compromise."},
{"text":"The token minority."},
{"text":"The Trail of Tears"},
{"text":"The true meaning of Christmas."},
{"text":"The Übermensch."},
{"text":"The Underground Railroad."},
{"text":"The unstoppable tide of Islam."},
{"text":"The violation of our most basic human rights."},
{"text":"The Virginia Tech Massacre"},
{"text":"The wonders of the Orient."},
{"text":"The World of Warcraft."},
{"text":"The wrath of Vladimir Putin."},
{"text":"Third base."},
{"text":"This answer is postmodern."},
{"text":"This year's mass shooting."},
{"text":"Those times when you get sand in your vagina."},
{"text":"Three dicks at the same time."},
{"text":"Throwing a virgin into a volcano."},
{"text":"Tickle Me Elmo."},
{"text":"Tickling Sean Hannity, even after he tells you to stop."},
{"text":"Tiger Woods."},
{"text":"Tom Cruise."},
{"text":"Toni Morrison's vagina."},
{"text":"Too much hair gel."},
{"text":"Twinkies®."},
{"text":"Two midgets shitting into a bucket."},
{"text":"Unfathomable stupidity."},
{"text":"Uppercuts."},
{"text":"Used panties."},
{"text":"Vehicular homicide."},
{"text":"Vehicular manslaughter."},
{"text":"Viagra®."},
{"text":"Vigilante justice."},
{"text":"Vigorous jazz hands."},
{"text":"Vikings."},
{"text":"Waiting 'til marriage."},
{"text":"Waking up half-naked in a Denny's parking lot."},
{"text":"Waterboarding."},
{"text":"Wearing underwear inside-out to avoid doing laundry."},
{"text":"Wet dreams."},
{"text":"When you fart and a little bit comes out."},
{"text":"Whipping it out."},
{"text":"White people."},
{"text":"White privilege."},
{"text":"White-man scalps."},
{"text":"Wifely duties."},
{"text":"Will Smith."},
{"text":"William Shatner."},
{"text":"Winking at old people."},
{"text":"Wiping her butt."},
{"text":"Women in yogurt commercials."},
{"text":"Women's suffrage."},
{"text":"World peace."},
{"text":"Yeast."},
{"text":"YOU MUST CONSTRUCT ADDITIONAL PYLONS."},
{"text":"Your weird brother."}];


export var BLACK_CARDS: BlackCard[] = [
{"text":"A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ______.", "spaces": 1},
{"text":"A romantic, candlelit dinner would be incomplete without ______.", "spaces": 1},
{"text":"After Hurricane Katrina, Sean Penn brought ______ to all the people of New Orleans.", "spaces": 1},
{"text":"After the earthquake, Sean Penn brought ______ to the people of Haiti.", "spaces": 1},
{"text":"Alternative medicine is now embracing the curative powers of ______.", "spaces": 1},
{"text":"And the Academy Award for ______ goes to ______.", "spaces": 2},
{"text":"Anthropologists have recently discovered a primitive tribe that worships ______.", "spaces": 1},
{"text":"BILLY MAYS HERE FOR ______.", "spaces": 1},
{"text":"But before I kill you, Mr. Bond, I must show you ______.", "spaces": 1},
{"text":"Coming to Broadway this season, ______: The Musical.", "spaces": 1},
{"text":"Daddy, why is Mommy crying?", "spaces": 1},
{"text":"Dear Abby, I'm having some trouble with ______ and would like your advice.", "spaces": 1},
{"text":"Due to a PR fiasco, Walmart no longer offers ______.", "spaces": 1},
{"text":"During his childhood, Salvador Dali produced hundreds of paintings of ______.", "spaces": 1},
{"text":"During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ______.", "spaces": 1},
{"text":"During sex, I like to think about ______.", "spaces": 1},
{"text":"For my next trick, I will pull ______ out of ______.", "spaces": 2},
{"text":"Fun tip! When your man asks you to go down on him, try surprising him with ______ instead.", "spaces": 1},
{"text":"Here is the church Here is the steeple Open the doors And there is ______.", "spaces": 1},
{"text":"How am I maintaining my relationship status?", "spaces": 1},
{"text":"How did I lose my virginity?", "spaces": 1},
{"text":"I do not know with what weapons World War III will be fought, but World War IV will be fought with ______.", "spaces": 1},
{"text":"I drink to forget ______.", "spaces": 1},
{"text":"I get by with a little help from ______.", "spaces": 1},
{"text":"I got 99 problems but ______ ain't one.", "spaces": 1},
{"text":"I never truly understood ______ until I encountered ______.", "spaces": 1},
{"text":"I wish I hadn't lost the instruction manual for ______.", "spaces": 1},
{"text":"I'm sorry, Professor, but I couldn't complete my homework because of ______.", "spaces": 1},
{"text":"In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?", "spaces": 1},
{"text":"In 1,000 years, when paper money is but a distant memory, ______ will be our currency.", "spaces": 1},
{"text":"In a world ravaged by ______, our only solace is ______.", "spaces": 2},
{"text":"In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ______.", "spaces": 1},
{"text":"In his new summer comedy, Rob Schneider is ______ trapped in the body of ______.", "spaces": 2},
{"text":"In L.A. County Jail, word is you can trade 200 cigarettes for ______.", "spaces": 1},
{"text":"In M. Night Shyamalan's new movie, Bruce Willis discovers that ______ had really been ______ all along.", "spaces": 2},
{"text":"In Michael Jackson's final moments, he thought about ______.", "spaces": 1},
{"text":"In the new Disney Channel Original Movie, Hannah Montana struggles with ______ for the first time.", "spaces": 1},
{"text":"Instead of coal, Santa now gives the bad children ______.", "spaces": 1},
{"text":"Introducing the amazing superhero/sidekick duo! It's ______ and ______!", "spaces": 1},
{"text":"Introducing X-Treme Baseball! It's like baseball, but with ______!", "spaces": 1},
{"text":"It’s a pity that kids these days are all getting involved with ______", "spaces": 1},
{"text":"Life for American Indians was forever changed when the White Man introduced them to ______.", "spaces": 1},
{"text":"Life was difficult for cavemen before ______.", "spaces": 1},
{"text":"Lifetime presents ", "spaces": 1},
{"text":"Major League Baseball has banned ______ for giving players an unfair advantage.", "spaces": 1},
{"text":"Make a haiku.", "spaces": 1},
{"text":"Maybe she's born with it. Maybe it's ______.", "spaces": 1},
{"text":"MTV's new reality show features eight washed-up celebrities living with ______.", "spaces": 1},
{"text":"Next from J.K. Rowling: Harry Potter and the Chamber of ______.", "spaces": 1},
{"text":"Next on ESPN2: the World Series of ______.", "spaces": 1},
{"text":"Rumor has it that Vladimir Putin's favorite dish is ______ stuffed with ______.", "spaces": 2},
{"text":"Sorry everyone, I just ______.", "spaces": 1},
{"text":"Step 1: ______. Step 2: ______. Step 3: Profit.", "spaces": 2},
{"text":"Studies show that lab rats navigate mazes 50% faster after being exposed to ______.", "spaces": 1},
{"text":"That's right, I killed ______. How, you ask? ______.", "spaces": 2},
{"text":"The class field trip was completely ruined by ______.", "spaces": 1},
{"text":"The new Chevy Tahoe. With the power and space to take ______ everywhere you go.", "spaces": 1},
{"text":"The Smithsonian Museum of Natural History has just opened an interactive exhibit on ______.", "spaces": 1},
{"text":"The U.S. has begun airdropping ______ to the children of Afghanistan.", "spaces": 1},
{"text":"They said we were crazy. They said we couldn't put ______ inside of ______. They were wrong.", "spaces": 2},
{"text":"This is the way the world ends, not with a bang but with ______", "spaces": 1},
{"text":"Today on Maury: ", "spaces": 1},
{"text":"TSA guidelines now prohibit ______ on airplanes", "spaces": 1},
{"text":"War! What is it good for?", "spaces": 1},
{"text":"What am I giving up for Lent?", "spaces": 1},
{"text":"What are my parents hiding from me?", "spaces": 1},
{"text":"What did I bring back from Mexico?", "spaces": 1},
{"text":"What did the U.S. airdrop to the children of Afghanistan?", "spaces": 1},
{"text":"What did Vin Diesel eat for dinner?", "spaces": 1},
{"text":"What do old people smell like?", "spaces": 1},
{"text":"What does Dick Cheney prefer?", "spaces": 1},
{"text":"What don't you want to find in your Chinese food?", "spaces": 1},
{"text":"What don't you want to find in your Kung Pao chicken?", "spaces": 1},
{"text":"What ended my last relationship?", "spaces": 1},
{"text":"What gets better with age?", "spaces": 1},
{"text":"What gives me uncontrollable gas?", "spaces": 1},
{"text":"What helps Obama unwind?", "spaces": 1},
{"text":"What is Batman's guilty pleasure?", "spaces": 1},
{"text":"What is George W. Bush thinking about right now?", "spaces": 1},
{"text":"What never fails to liven up the party?", "spaces": 1},
{"text":"What will always get you laid?", "spaces": 1},
{"text":"What will I bring back in time to convince people that I am a powerful wizard?", "spaces": 1},
{"text":"What would grandma find disturbing, yet oddly charming?", "spaces": 1},
{"text":"What's a girl's best friend?", "spaces": 1},
{"text":"What's my anti-drug?", "spaces": 1},
{"text":"What's my secret power?", "spaces": 1},
{"text":"What's Teach for America using to inspire inner city students to succeed?", "spaces": 1},
{"text":"What's that smell?", "spaces": 1},
{"text":"What's that sound?", "spaces": 1},
{"text":"What's the crustiest?", "spaces": 1},
{"text":"What's the most emo?", "spaces": 1},
{"text":"What's the new fad diet?", "spaces": 1},
{"text":"What's the next Happy Meal toy?", "spaces": 1},
{"text":"What's the next superhero?", "spaces": 1},
{"text":"What's the next superhero/sidekick duo?", "spaces": 1},
{"text":"What's there a ton of in heaven?", "spaces": 1},
{"text":"When I am a billionare, I shall erect a 50-foot statue to commemorate ______.", "spaces": 1},
{"text":"When I am President of the United States, I will create the Department of ______.", "spaces": 1},
{"text":"When I was tripping on acid, ______ turned into ______.", "spaces": 2},
{"text":"When I'm in prison, I'll have ______ smuggled in.", "spaces": 1},
{"text":"When Pharaoh remained unmoved, Moses called down a Plague of ______.", "spaces": 1},
{"text":"While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ______.", "spaces": 1},
{"text":"White people like ______.", "spaces": 1},
{"text":"Who stole the cookies from the cookie jar?", "spaces": 1},
{"text":"Why am I sticky?", "spaces": 1},
{"text":"Why can't I sleep at night?", "spaces": 1},
{"text":"Why do I hurt all over?", "spaces": 1},
{"text":"When I'm in prison, I'll have ______ smuggled in.", "spaces": 1},
{"text":"Who stole the cookies from the cookie jar?", "spaces": 1}];
